# Generated by Django 4.0.6 on 2022-08-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(height_field=259, upload_to='restaurant_images', width_field=194),
        ),
    ]
